Add authentication | Password resetting requires further debugging
chingu-voyages/v42-bears-team-41 pull request #32
Opened 2023-02-03 19:36 UTC by ultracodez

Password resetting is broken, someone needs to debug that.

2023-02-03 21:29 UTC, ElijahBcodes approved these changes

2023-02-03 21:32 UTC, ElijahBcodes requested changes
merge conflicts in src/pages/index.js

2023-02-03 22:02 UTC, ElijahBcodes approved these changes
Nice!!

2023-02-04 01:32 UTC, merged

2023-02-04 01:32 UTC, ultracodez commented
@ElijahBcodes, don't delete this branch, I may require rolling back to fix the `/reset` route later on.